// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { DATABASE_URL, SHADOW_DATABASE_URL } from "./src/lib/dotenv";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: DATABASE_URL,
        shadowDatabaseUrl: SHADOW_DATABASE_URL,
    },
});
