name: Release on GitHub

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: '0' #fetches full history for changelog generation

      - name: Get version from package.json
        id: get-package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "raw_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: tag-check
        run: |
          if git tag -l "${{ steps.get-package-version.outputs.version }}" | grep -q "${{ steps.get-package-version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub release
        if: steps.tag-check.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.get-package-version.outputs.version }}" \
            --title "${{ steps.get-package-version.outputs.version }}" \
            --generate-notes \
            --latest